### ISSUE TITLE
Review workspace as output placeholder

### ISSUE THREAD

**Issue by adrianriobo** [redhat-developer/mapt#319]
This is an opinionated way to define how wokspaces should maintain the host information to be used by other tasks.

Typically we use a secret structure which can be represented as a workspace:

```yaml
- name: host-info
  description: |
    ocp secret holding the hsot info credentials. Secret should be accessible to this task.
    ---
    apiVersion: v1
    kind: Secret
    metadata:
      name: XXXX
      labels:
        app.kubernetes.io/component: XXXX
    type: Opaque
    data:
      host: XXXX
      user: XXXX
      password: XXXX
      key: XXXX
      platform: XXXX
      os-version: XXXX
      arch: XXXX
      os: XXXX
  mountPath: /opt/host/
```
